### ISSUE TITLE
Teleporter

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#114]
Turns out that the teleporter select is displaced one spot to the left and has rendering issues.

**Comment by andwhyisit** [comment]
Hmm.. this seems to be happening on converted saves only (prof2sram and the level selector).

**Comment by andwn** [comment]
![screenshot_2017-02-21_14-32-20](https://cloud.githubusercontent.com/assets/8164394/23181367/c039df8a-f842-11e6-9972-48e0599d1710.png)
This is something special. Would you happen to have a non-converted equivalent of one of the saves so I can compare the teleporter section in bindiff? If not it's fine I have to make another pass through the game to replace the level select files eventually.

**Comment by andwhyisit** [comment]
Here's my save from my holiday test run (after I trudged back from the prefab building to Arthur's house):
http://www.mediafire.com/file/gb14xssywtypgs7/doukutsusrm.zip

By the way, the level select files that definitely need replacing are "Balfrog" and "Mimiga Village", because both are 3hp saves.

**Comment by andwn** [comment]
Comparing with a later converted save it seems the first teleporter location is always blank when the game itself saves it. Probably the root of the problem is I assumed whatever the TSC command to change the locations accepts "0000" as a valid entry where it starts at "0001" in the original game.

I'm just going to adjust prof2sram to work around it instead since there are never 8 teleporter locations anyway.
