### ISSUE TITLE
Balcony Ravil Projectiles and Lag Bats (Muscle Doctor)

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#127]
The Bubbler discussion gives me an idea for two of the more lag-inducing elements of the game: the Igor clone on the Balcony and the bats during the Muscle Doctor fight. Why not have two bats/projectiles in one sprite and double the hp and damage received? Also have it that when the double bat/projectile object reaches half the hp it can halve the damage received, reduce the hitbox, and switch to a single bat/projectile sprite.

Is this possible or am I fundamentally mistaken about how this all works?

**Comment by andwn** [comment]
I was just going to make there be a few less bats/projectiles. Worst case do the [jellyfish hack](https://github.com/andwn/cave-story-md/blob/master/src/ai/weed.c#L27) though I would prefer to avoid it.

The smaller Ravil is still missing from Balcony I should probably add it.

**Comment by andwhyisit** [comment]
The smaller Ravil was missing from the Grasstown hut as well last I checked.

**Comment by andwn** [comment]
When I went in there the door didn't lock and there was no boss music. Never really investigated the reason. The answer must be in the TSC.

**Comment by andwhyisit** [comment]
The door doesn't lock in the original. You can skip the mini boss fight entirely by walking out the door.

**Comment by andwhyisit** [comment]
Regarding the jellyfish hack, wouldn't it be better to have the non-shootable frame be the frame directly after the jelly was shot while in a shootable state, or am I missing something here?

**Comment by andwn** [comment]
Every shootable object checks for collision with every player bullet every frame. One object skipping that check once after it gets shot wouldn't improve the speed at all, but every object of a specific type, where 10 of that object type are on the screen, skipping that every other frame actually did speed it up.

One day I would like to come back to this and remove the need for the speed hack. Rewriting the hard hitting parts in asm because GCC is *really* bad about optimizing for m68k, but writing asm is a struggle for me. There is a learning curve I need to climb before I can do this.

**Comment by andwhyisit** [comment]
Now that I understand how and why it works it makes sense. I can't think of a condition where a bullet's collision wouldn't last for more than one frame.

**Comment by andwn** [comment]
It could effect the Missiles (after exploding), Blade Lv3 (King part in the center) and Spur since those are implemented as AOE. Actually thinking more about this, the framerate of NTSC vs PAL will effect that too. I'll have to do something to compensate for that for the high HP enemies and bosses where that will be a noticeable thing.

**Comment by andwhyisit** [comment]
Ouch.

In any case this issue seems to be fixed. So I'll mark it as such.
