### ISSUE TITLE
Misery Fight Crashes the Game

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#134]
![](http://i214.photobucket.com/albums/cc164/andwhyisit/mizacrash_zpsifihr0os.gif)

It specifically happens during the black lightning animation.

On subsequent testing it seems to also happen if the black orb projectiles and black lightning orbs are on the screen at the same time.

**Comment by andwn** [comment]
I can't get this to happen, maybe we are doing something different. I tried BlastEm, Gens, PAL, NTSC, with all weapons, but never opened the menu nor purposely got hit by the lightning.

**Comment by andwhyisit** [comment]
The weapon used against Misery was the machine gun exclusively. The build is ntsc, and the emulator is gens. I never opened the menu either and was never hit by lightning. In fact the game dies on spawning the lightning, so it has no chance to ever hit me. The music continues to play after the game hangs, which is weird. Save used was the Balcony save from the level select with all weapon levels raised to 3.

I could record the fight right up until the crash tomorrow if you prefer. I've been able to reproduce the error pretty consistently, so it shouldn't be too difficult.

**Comment by andwn** [comment]
I've spent 2 hours on this now and don't really get it. I've downloaded the nightly and it happens there, but only if I wait at the very left side of the map for a while and Misery shoots from the far right.

On my local build it is not reproducible no matter what I do.

**Comment by andwhyisit** [comment]
Alright, recordings it is:
http://i214.photobucket.com/albums/cc164/andwhyisit/mizacrash1_zpszbw0wsmc.gif
http://i214.photobucket.com/albums/cc164/andwhyisit/mizacrash2_zpsybqy7p5m.gif
http://i214.photobucket.com/albums/cc164/andwhyisit/mizacrash3_zpsl4b2fpdo.gif
http://i214.photobucket.com/albums/cc164/andwhyisit/mizacrash4_zpsus5azdz4.gif
(these gifs are fucking huge btw, I left nothing out)

Maybe it has something to do with the new camera panning?

**Comment by andwn** [comment]
I swear I'm not crazy.

[doukutsu.zip](https://github.com/andwn/cave-story-md/files/819391/doukutsu.zip)
https://www.youtube.com/watch?v=CUIgf5U4CvE

**Comment by andwn** [comment]
I got this error to come up in a random spot unrelated to Misery (PC=102). Looking back at the Sand Zone crash it is also the same.

Something super fun is happening.

**Comment by andwhyisit** [comment]
Well I can't seem to reproduce this anymore during the Misery fight in the latest builds.

Where did it come up for you?

**Comment by andwn** [comment]
It came up leaving Egg 1 after disabling the barrier, while trying to verify some changes to the message window.

I have an idea as to what the cause is but still poking around at it.

**Comment by andwhyisit** [comment]
Is it something to do with the rewrite you are working on?

**Comment by andwn** [comment]
Rewrite is a bit strong of a word for that branch. I was merging SGDK into the main program so I could change things about it, including a structure change that should make this certain kind of random crash impossible (playing "where did I forgot to disable interrupts this time?"). Hopefully it will have been worth the effort.

I'm happy that I got everything to work as it does in master again, but want to see if there is something I can do about the one "side effect" before bringing it back in. That being the music will slow down with the gameplay when too much is going on, since everything is running (except toggling one flag) in one linear main loop.

Worst case I drop it and continue on with what is in master right now.
