### ISSUE TITLE
[Items] Collectibles that 'time out' and disappear do not do so if off screen

### ISSUE THREAD

**Issue by EvilTelephone** [andwn/cave-story-md#14]
For example: experience gems. They'll survive being off screen until you transition to a new area or remain next to them and wait for the time out period.

**Comment by sikthehedgehog** [comment]
I think this problem is in the original game as well though.

**Comment by EvilTelephone** [comment]
I tested it with Cave Story Plus (which may not be a great idea, in hindsight) and it wasn't the case. I'll have to test with the original.

If the problem is in the original, then I'll close this out with a "nevermind!" :)

**Comment by EvilTelephone** [comment]
Update: I tested with the original and the experience gems still have their logic even far off screen. You can even hear them 'plinking' as they bounce.

This may end up being a needed change to facilitate the hardware, but I figured I'd add it to the list just in case.

**Comment by sikthehedgehog** [comment]
Huh, I'm pretty sure I stumbled upon this behavior in a Cave Story game way before here, so it's definitely not unique to this port. (I just wish I could remember the name of that game, argh, plays pretty much the same but plot and maps are different)

**Comment by andwn** [comment]
Almost all offscreen objects (save for bosses and special cases to unbreak things) are shelved into an "inactive" list until coming back on screen. The original cave story does not do this, it just updates everything in the room every frame because PCs are powerful. If I refactor items into their own list I could probably update the timers offscreen without lag but I don't care enough to do this.

A bit of backstory: Until 2-3 weeks ago the energy never expired. I added it because of the sections in grasstown and sand zone that basically guarantee energy will fall down into death traps, potentially resulting in a framerate drop as they accumulate.

There are other things I plan to do to optimize the energy though, maybe the expiration won't be needed in the future. For example the small bits are 2x2 tiles and should really only be 1x1. That's just using unnecessary DMA bandwidth.

**Comment by andwn** [comment]
Checking back with the original the items do disappear after a while. I made all the power ups persistent (will stay active offscreen) and they delete after 10 seconds.
