### ISSUE TITLE
Toroko+ Fight

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#146]
The behaviour in this room is extremely different based on which build you are using.

**NTSC:**
The storehouse has exploding map syndrome on the ntsc build:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/graffitigonemad_zpsjjyw5ueu.gif)

This is consistent as far as I can tell. I cannot enter the door without this happening.

**PAL:**
The pal build on the other hand mangles the flowercub pallettes and inserts a random 8x8 tile on the bottom-left corner of Toroko:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/lookatmetwoblocksatonce_zps1q8wjsgv.gif)

The location of the 8x8 tile is always the same in relation to Toroko.

When exiting the room the screen either goes black or produces this error:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/onexit_zpsoj3kwqar.gif)

Dying and retrying also either makes the screen black or produces a 102:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/ondeath_zpsjqbm09p3.gif)

**Comment by andwn** [comment]
Predictably, a local build doesn't do this, but trying the NTSC nightly in BlastEm gives me an "ADDRESS ERROR" immediately when entering the door (Gens does not emulate address errors).

I'm talking specifically about the crash here, the random block/palette stuff still happens.

[doukutsu.zip](https://github.com/andwn/cave-story-md/files/852477/doukutsu.zip)

I'm gonna just try a bindiff on the ROMs. Do you still have the symbol.txt generated from the build? Well, it's probably overwritten by the PAL one... I'll have to rename the outputs based on standard sometime later.

**Comment by andwhyisit** [comment]
At 0x26F 3 bytes are changed.

At 0x28F 3 bytes are changed.

At 0x296 2 bytes are changed. This repeats every 6 bytes up until 0x34C.

At 0x35B 3 bytes are changed. This repeats every 20 bytes up until 0x3FE.

At 0x41B 3 bytes are changed. This repeats every 6 bytes up until 0x442.

At 0x468 2 bytes are changed.

From 0x1B7A onwards everything goes to the shitter and there is nothing in common whatsoever.

The nightly has 5636 bytes less whitespace at the end of the file.

The nightly is 57344 bytes smaller (or 51708 if you exclude said end of file whitespace).

Some of the data is in a completely different order in the nightly. In the nightly rom the location names and song names come after the credit text, whereas they come before in your build.

**Comment by andwn** [comment]
I can understand the order being different since make/gcc don't enforce a file listing order but.. 50KB smaller :open_mouth: 

Well at least I was able to fix the other issues with that room Today...

**Comment by andwhyisit** [comment]
Uhh.. I just did a force rebuild after changing the nightly generation script to include symbol.txt in the zip file.

Everything is working. Including the balcony.

Apparently disabling lz4w did the trick.

**Comment by andwn** [comment]
wat

I'm gonna use something other than lz4w for compression next time.

**Comment by andwn** [comment]
There was a time a long time ago when I first started using compression where maps would randomly explode all the time. I worled around it by rearranging the stage loading so that everything from the old map gets completely unloaded, then the tileset for the next map gets decompressed before anything else. I don't actually know how lz4w works so maybe you are onto something, though we're rebuilding rescomp every time now (which calls lz4w to do the compression), and using the same jar...

By the way do you know the RedHat/CentOS package names for the dependencies? Something like `sudo yum install wget unzip build-essential texinfo python`. The build-essential is Debian's name for the package including GCC, binutils, make, etc I assume it is named differently here.

**Comment by andwhyisit** [comment]
This might work maybe:
http://wiki.telefang.net/Wikifang:Telefang_1_Translation_Patch/Malias_compression

This is for a gameboy game, but I assume it can be adapted?

You of course need to check if the compressed data is smaller than the raw data. If the compressed data is larger than the raw data then use the raw data instead.

I honestly can't remember what I used instead of build-essential. Java was named differently though. Everything else looks to be the same. I learnt about the dependencies the hard way, by waiting for the build to fail (you can imagine what that was like when building gendev for the first time, given that it takes 2 hours for the build to reach that stage). I never paid them any thought after that.

**Comment by andwn** [comment]
I googled around and apparently `yum groupinstall 'Development Tools'` is the equivalent, so that's going into the readme now.

For compressing stuff I was going to try [this](https://github.com/sikthehedgehog/mdtools/tree/master/uftc) though it may not be necessary since there is enough space for the rest of the game already.

**Comment by andwhyisit** [comment]
**I think that this is build-essential:**
yum groupinstall "Development Tools"

**Comment by andwhyisit** [comment]
Java was "java-1.7.0-openjdk" for the JRE.

**Comment by sikthehedgehog** [comment]
If you're going to change the compression format you may as well just use SLZ:
https://github.com/sikthehedgehog/mdtools/tree/master/slz

I admit, I'm not 100% sure that the C decompression routine works :P but I can guarantee the the asm one does because I use it all the time (wrapping around it would be best for reducing loading times anyway). And the compression tool is written in C, no dependencies needed.

It's the same compression format I've been using since Project MD, if you wonder.

**Comment by andwhyisit** [comment]
Might as well close this.
