### ISSUE TITLE
Invincibility cheat improvements

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#152]
First off, you can still get OHKO'd if the amount of damage dealt is more than your current health.
This should probably be disabled, except for insta-death spikes (since not getting killed by those basically renders you stuck).

Also, weapon XP should probably not get reduced.

**Comment by andwhyisit** [comment]
I agree on the point of weapon xp not going down.

However the spikes you are talking about aren't insta-kill, they just cause 127 damage. They are only insta-kill in the sense that the small spikes (5 damage) are insta-kill when you only have 3hp.

A better exception would be to allow any damage amount of 64 or greater instead of writing specific code for large spikes.

**Comment by andwn** [comment]
This was supposed to be a temporary thing because getting to the undead core over and over again was annoying... you think I should keep it?

**Comment by Leo40Git** [comment]
Sure, why not? Of course, in the final game the cheat would be harder to unlock/activate.

**Comment by andwhyisit** [comment]
I'm not going to argue for or against permanent inclusion, but weapon xp not being reduced would certainly make it easier to repeatedly and exhaustively test a boss fight. The rest of it is a non-issue for me.
