### ISSUE TITLE
Add multiple save slots

### ISSUE THREAD

**Issue by hadess** [andwn/cave-story-md#198]
So that multiple people can play the game concurrently.

**Comment by Leo40Git** [comment]
The save files are pretty big due to the 8000 flags each of them has to store, so this might not be possible due to limited SRAM space.

**Comment by andwn** [comment]
I have been planning to do this for a while. There is 32kb which is plenty.

**Comment by sikthehedgehog** [comment]
> The save files are pretty big due to the 8000 flags each of them has to store, so this might not be possible due to limited SRAM space.

Are the flags boolean? Because that'd require only 1000 bytes then.

And yeah, most emulators and pretty much all flashcarts limit save data to 32KB. No idea how much space a Cave Story save takes up though :P (@andwn said it fits so...) Just make sure that there's enough spare room to store any data for recovery in case of failure (e.g. console shuts down right in the middle of saving, leaving a partially written file)

**Comment by andwn** [comment]
Cave Story only uses 4001 of those 8000 flags, so I only store 512 bytes, and that's the bulk of the save data. The annoying part is writing another UI.

**Comment by SkyTheLeafeon** [comment]
I think this issue needs to be closed. 0.5.0 was the first build to introduce multiple saves.

**Comment by andwn** [comment]
Yep. Surprisingly I only needed 8KB for 4 files + backups, on top of the config and space for the counter.
