### ISSUE TITLE
[Suggestion] Add Switch enchancements?

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#200]
Because why not add puppy stacking? Also:
- Multiple jellies in inventory at once
- Waterway: fix tile configuration to prevent overshooting the cabin
- Labyrinth M (the one with Booster falling): add way to get back up without having to restart
- Skip cutscene feature?

**Comment by andwhyisit** [comment]
Puppy stacking means more entities on screen at once. This port is already struggling as it is.
Labyrinth M and Waterway involves copying tile layouts and events from the Switch port, which isn't worth risking.
And the skip cutscene button already exists.

**Comment by Leo40Git** [comment]
Isn't the current "skip cutscene" (actually fast forward) button a debugging feature?
Totally understand the other problems with my suggestion, though.

**Comment by andwn** [comment]
The FFwd is there because I wanted to add cutscene skipping but it isn't feasible without making a lot of TSC changes. There are a lot of things that change what happens in the update loop (AI) rather than applying some set change, for example when first falling into Mimiga Village. The script puts quote above the screen and waits a couple seconds for the fall. Ignoring all the <WAIs and other things which take time would leave the player in the wrong spot.

The other stuff I'm not sure. People could get mad if I change that stuff (and Nicalis too). I've been trying to keep it close to the original, so things like chaco's house & sisters skip work. Then again we have controller remapping and multisave now so eh..

**Comment by Leo40Git** [comment]
Actually, it seems that CS+ Switch's "skip cutscene" feature is *also* a fast forward button. Huh.

**Comment by andwn** [comment]
I'd brag about giving them the idea, but they probably came up with it themselves.

**Comment by Leo40Git** [comment]
CS+ Switch lets you lock Quote's direction by holding a button. That seems like a somewhat easy thing to implement.

**Comment by andwhyisit** [comment]
The switch can pull this off easily because it has two sets of shoulder buttons. The MD has none. You can't hold a face button while pressing another, that would just cause hand cramps. The only way to pull this off is to have a button that when pressed once would enable directional lock, and then disable it when pressed again. The problem with this is that people who press it accidentally will be wondering what the heck is going on. So it would have to be a non-default button config option if it were to ever work. It would also need an HUD indicator of if directional lock is or isn't enabled.

**Comment by Leo40Git** [comment]
Yeah this probably won't happen.
