### ISSUE TITLE
(Suggestion) Controller modes

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#217]
Maybe there should be an option under Config that allows the player to choose between the three-button and six-button controller modes.

**Comment by andwn** [comment]
Shouldn't bee too hard to do something like this, but gonna research some stuff about controller modes and try to find the cause of #211 so I can decide if it's necessary.

People have told me the mode button changes how the controller presents itself to the console, but when I press it nothing happens (the SGDK-based code I use to update the controller states checks the mode per frame).

**Comment by sikthehedgehog** [comment]
Holding down the Mode button *when turning on the console* makes it
simulate a 3 button controller (this is intended for compatibility with
some older games). Otherwise it's just one more button.

That said, I imagine that providing both schemes may still be useful just
in case somebody prefers pressing A despite having a 6 button controller.
No need to force them to remember to hold down Mode every time they want to
play.

**Comment by andwn** [comment]
Well that explains a lot. Guess the option would be 3 way like this:

"Force controller mode" : OFF / 3btn / 6btn

**Comment by SkyTheLeafeon** [comment]
That sounds good. Looking forward to it!

**Comment by andwn** [comment]
Well, I didn't implement it yet so, should probably keep it open until then.

**Comment by SkyTheLeafeon** [comment]
Oh, good point! My apologies.

**Comment by andwn** [comment]
0.5.1
![blastem_2018-03-17_17-59-09](https://user-images.githubusercontent.com/8164394/37560366-e796a91c-2a0c-11e8-892f-3803b4a5c043.png)
