### ISSUE TITLE
Fatal error at launch !

### ISSUE THREAD

**Issue by kenan1099** [andwn/cave-story-md#229]
Build 6/3 crashes at startup (after balrog animation) .
Text displayed :

A fatal error occurred !
Cannot continue .....
Too many events : 255

**Comment by andwn** [comment]
What emulator/flash cart? (it doesn't happen to me in BlastEm)

**Comment by kenan1099** [comment]
Retro arch w/ genesis gx plus core
I also tried a standalone genesis gx plus emulator and it gave the same error
However it worked with Pico drive 
(Btw , emulated on an android phone)

**Comment by andwn** [comment]
I tried both nightly and a current build. Both crash with that error in Genesis Plus GX, and don't crash on my US model 2 (or the other 4 emulators I tried).

Added an extra note on the location of the TSC in the error message. The address it's getting the "255" from is different each time I build the game but seemingly random. Spent a good hour trying to figure out what the reason is (it doesn't like the way SRAM is mapped?) but I give up.  If it works on hardware it's the emulator's fault.

**Comment by SkyTheLeafeon** [comment]
Oh, my.

**Comment by kenan1099** [comment]
Note taken : Genesis gx plus sucks and nobody should use it.
Yet sadly it comes as the first option when searching "genesis emulator" on Google play....
If you truly give up , it is understandable, but atleast do make a note on "readme" that it won't work on Genesis gx / Genplusdroid .
Anyways , gx just sucks and has many problems (especially with sound...) so I think just writing a note should be enough :)

**Comment by andwn** [comment]
Is the app really called "gx plus" instead of "plus gx"? Sounds bootleg. Anyway, the retroarch one is legit. I'm going to try and report the issue.

**Comment by sikthehedgehog** [comment]
It's Genesis Plus GX yeah.

The problem is that it's outdated. Eke already fixed a lot of things to
make Overdrive 2 work long ago (which presumably may fix some other issues
like that too) but they still haven't made their way to a proper release.
Not sure why, "fixes OD2" seems already good enough of a milestone for a
new release.

**Comment by andwn** [comment]
Ehh I'll just add a note for now and worry about it later. When either GX updates or this project is almost done.

**Comment by hizzlekizzle** [comment]
Hey, just noticed the note and went to test it. GenPlusGX in RetroArch seems fine here.

**Comment by andwn** [comment]
That's good news. I think I'll give it a try. Maybe we can finally get rid of that note about GX being broken.
