### ISSUE TITLE
The orange guy with the knife in the Graveyard can't be shot until he begins attacking you

### ISSUE THREAD

**Issue by EvilTelephone** [andwn/cave-story-md#23]
Projectiles pass right through him until he enters "attack mode".

Emu used: Genesis Plus GX
Rom version: SNAPSHOT-2016.07.16

**Comment by andwn** [comment]
I was thinking "That's not how it works in the original?" and apparently it's not. You have to attack from behind.

http://cavestory.wikia.com/wiki/Gravekeeper

I'll try to fix that in the next release.

**Comment by andwn** [comment]
I compared what I do to NXEngine and it actually does have to be shot while it is attacking with the knife. However I forgot to implement the "invincible" flag which makes enemies block shots with a "tink" noise, rather than just ignoring them (that's why shots pass through). This should be fixed once I upload a new release, probably tomorrow.

**Comment by andwn** [comment]
Closing this relic of the past
