### ISSUE TITLE
Bubbler not working in some parts of Grasstown

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#231]
When firing the Bubbler on certain slopes, it won't shoot at all. Another thing I should've mentioned earlier.

**Comment by andwn** [comment]
This was happening for the weirdest reason

**Comment by SkyTheLeafeon** [comment]
How odd...

**Comment by andwn** [comment]
I didn't get notified of that edit at all, but the reason is I had a check like this for collision:

`if((block_at_bullet_position & 0x41) == 0x41)`

0x41 is the tile attribute for a solid foreground tile. I wanted to match 0x43 (breakable) as well, but messed up the check and also matched some tiles for slope (0x21, 0x23, 0x25, 0x27). It should have been this instead:

`if(block_at_bullet_position == 0x41 || block_at_bullet_position == 0x43)`

I also could have given these friendly names instead of matching the numbers but eeeh.
