### ISSUE TITLE
Game Over and Cemetery themes could sound better

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#238]
Same issue as the Running Hell theme, but as you said, the xgm files are available for edits.
(The Game Over theme could very easily be improved.)
The Cemetery theme's tempo is slightly too fast - the PC version's is a little slower.

**Comment by SkyTheLeafeon** [comment]
Also, Pulse is a tad too slow. (Same for Geothermal and the title screen/plantation theme, I think.)
Is it just me, or does Moon Song sound an octave too low?
Waterway sounds a tad too fast as well.
(Literally skimmed through the sound test for this.)

**Comment by andwn** [comment]
Not really concerned with the music right now. Just making these took 5-10 hours per track. I know about most of this but just don't care.

**Comment by SkyTheLeafeon** [comment]
Understandable. Such things can be fixed before final, I'm sure, but that's kinda up to you since this is not my project.

**Comment by andwn** [comment]
I'm going to reply to these individually.

Cemetery/Pulse - I'll mess with the tempo sometime Today. Sometimes it isn't quite possible to get the exact tempo in Deflemask, so I would just try to make it as close as possible.
Game Over - You didn't actually say what was wrong with it.
Geothermal/Plantation - I actually don't have the source files for these, since someone else covered them (annoying because part of Plantation is missing).
Waterway - The thing with this one is once I open it I'll want to fix the volume levels of some parts and that could take a while (Grasstown too actually).
Moonsong - I think the instrument I was using sounded too high in the next octave but don't really remember.

**Comment by andwn** [comment]
I've messed with the instruments and speeds of some tracks that I thought sounded not so good after finishing Toroko and King's themes. Will probably adjust others as I notice things.

Anyway, no more "your covers suck" issues please.
