### ISSUE TITLE
Some (a lot, really) other things I forgot to mention

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#239]
There are droplets of water that fall from the ceilings of the First Cave, which are presently absent in the port.
Same goes for the splash effect when entering water.
The exp bar is supposed to flash when collecting experience, and the numbers that appear for when the player collects experience/takes damage are supposed to follow Quote (above his head).
Additionally, when taking damage, the portion of the HP bar that's taken away by said damage is supposed to turn yellow upon said damage being taken, and then that yellow portion slides backwards to the end of the remaining red portion. Same for boss HP bars, which are supposed to span across the bottom line of the screen instead of just occupying a corner.
Also, some enemies drop a lot more exp than they do in the port, and a lot of the animations are different as well.
There should also be a small, reddish background to the HP icon and number.
Also, shots from the Polar Star (haven't tested further) aren't supposed to go through those tiny slopes, like those close to the Start Point's external door. Those shots also are supposed to have a much shorter range (at level 1, at least.)
Also, aren't there specific fade transitions?

Compared to Cave Story+.

**Comment by andwn** [comment]
I feel like you have already mentioned some of these before but

>There are droplets of water that fall from the ceilings of the First Cave, which are presently absent in the port.

Procrastination makes perfect

>Same goes for the splash effect when entering water.

This is in 0.5.1. It's not exactly the same, but I don't care about it being perfect.

>The exp bar is supposed to flash when collecting experience
>Additionally, when taking damage, the portion of the HP bar that's taken away by said damage is supposed to turn yellow upon said damage being taken, and then that yellow portion slides backwards to the end of the remaining red portion.

The blinking I have been thinking of putting in, but the rest I left out due to the complexity required. I probably can't explain it well, but basically everything must be drawn as 8x8 tiles. Here is the sprite sheet for the bars:
![hudfill](https://user-images.githubusercontent.com/8164394/37567967-fdc2188c-2aa4-11e8-8af7-7d386ea1d534.png)

It's impractical to use this method for an HP bar that shows new damage as yellow, and I'd rather not rewrite the HUD code to do bit twiddling to fill in columns, not to mention it's going to waste way more cycles than using the sheet.

>[...] boss HP bars [...] are supposed to span across the bottom line of the screen instead of just occupying a corner.

This is on purpose. The sprite can't be that long, and if it were a window, it would cut off the level.

>the numbers that appear for when the player collects experience/takes damage are supposed to follow Quote (above his head).

This also applies to enemies. It's possible to do, probably.

>Also, some enemies drop a lot more exp than they do in the port

They drop the same number of exp points, but only one triangle per enemy (3 guesses as to why). This is documented in DIFFERENCES.md.

>a lot of the animations are different as well

?

>There should also be a small, reddish background to the HP icon and number.

I feel like this will look like a red blur on a CRT (more so than just a heart).

>Also, shots from the Polar Star (haven't tested further) aren't supposed to go through those tiny slopes, like those close to the Start Point's external door.

Some objects (mostly any bullet that isn't a fireball) don't collide with slopes due to the heightmap checking taking some time. With the polar star it probably wouldn't be a big deal so I'll try adding it in. Some weapons like machine gun and bubbler can have a lot at once so it could actually become a problem.

>Those shots also are supposed to have a much shorter range (at level 1, at least.)

It is shorter in 0.5.1

>Also, aren't there specific fade transitions?

You mean in different directions?

**Comment by SkyTheLeafeon** [comment]
Responses to each:
-I see.
-Understandable.
-...I see.
-I see.
-Gotcha.
-I see.
-Some of the animations look different to me. It might just be because a lot of them are slower than they are in the PC version.
-Considerable.
-I see.
-This post is a tad old - that's one of the things that got fixed.
-Yes.

**Comment by andwn** [comment]
I think the only actionable thing left in here is the water drops in first cave (and probably other places) so I'll keep it open until I do that.

**Comment by andwn** [comment]
Water drops have been in for a while now
