### ISSUE TITLE
Intro disclaimer

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#242]
Every Sega Genesis/Mega Drive starts up with the words "PRODUCED BY OR UNDER LICENSE FROM SEGA ENTERPRISES LTD." on startup.
I think there should be a disclaimer before the Sega screen that states that this port is fan-made, not produced by or under license from Sega, and that all rights to the original game belong to its owners.
Fair use stuff, really. I should've said this WAY earlier.

**Comment by andwn** [comment]
My understanding is that only commercial games for the system need anything like that. Though the "presented by studio pixel" message should probably be changed.

**Comment by SkyTheLeafeon** [comment]
Maybe it should say "Ported by Andy Grind" as well?

**Comment by andwn** [comment]
I looked into this more and it seems these kind of disclaimers do absolutely nothing legally, and are mostly done either because of misunderstanding copyright law or because someone thinks it looks cool. If Nicalis or Sega believe that this port is losing them money or hurting their image they can force me to take it down. The disclaimer makes it even worse because it is proof of "willful infringement". But hey maybe it is different in some other countries.

I still think it might be a good idea to point out this is a fan work and that Pixel is not to blame for anything I break.

**Comment by sikthehedgehog** [comment]
Sega v. Accolade completely trashed the effectiveness of TMSS, for what's worth it (not to mention the fact that the screen doesn't even show up on every console)
https://en.wikipedia.org/wiki/Sega_v._Accolade

But yeah, Pixel owning the copyright is probably a whole different matter to care about. Especially since I don't know how much Nicalis actually owns aside from (obviously) not having rights to the original freeware PC release (do they own exclusive rights to make any other releases or what?).

**Comment by andwn** [comment]
I don't think he would care unless it was Kero Blaster, since that's actually sold.

Only real questionable feature I have (as in doesn't exist in freeware, but does in plus) is the multiple saves, but I feel like that's something you need in a console game.

**Comment by SkyTheLeafeon** [comment]
Four save files... one for every ending, I guess. I think there's supposed to be three? I don't remember.

**Comment by andwn** [comment]
For this, I put "Based on the Work of Studio Pixel"
