### ISSUE TITLE
(Suggestion) Fadeout when skipping intro?

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#249]
The same for when the intro normally ends, perhaps? That'd polish the intro itself a little.

**Comment by SkyTheLeafeon** [comment]
And also perhaps a fadeout and a fadein to the sound test and config screens, and fadeouts from them?

**Comment by andwn** [comment]
I feel like between menus a fade is unnecessary, but for the intro yes. Maybe I'm just so used to the fade not being there for the sound test in 3 years.

**Comment by andwn** [comment]
Also, the intro *does* currently fade out if you wait for it to end.

**Comment by SkyTheLeafeon** [comment]
I see. Perhaps, once this gets to beta, the fade transition animations seen in the PC version can be added. But, that depends entirely on whether or not the Genesis can handle that, and whether or not the ROM has enough space for them.

**Comment by andwn** [comment]
I did make a note of the fade effect in DIFFERENCES.md. Originally it just said I won't do it but have recently been thinking about how it can be achieved.

**Comment by SkyTheLeafeon** [comment]
Gotcha.

**Comment by andwn** [comment]
Actually, the intro is fading when I skip it.
![blastem_2018-03-18_01-04-48](https://user-images.githubusercontent.com/8164394/37562850-62c2dc88-2a48-11e8-8fce-51e78be6271c.png)

Only part that doesn't is the text because that's just how I made the fades work (if it's not immediately obvious why, here is a screenshot demonstrating the reason).
![blastem_2018-03-18_00-27-37](https://user-images.githubusercontent.com/8164394/37562592-30e7a090-2a43-11e8-853c-65afedb4c3b6.png)

There is probably a full black palette lying around I could use just for the intro if the text is annoying.

I've also thought more about the PC fading and I really think it isn't going to happen. It's not a matter of ROM space, but how to display both plane A and B (level and background) while the fade animation is happening. The window plane won't work, because it overlaps A, making the level invisible (Like what happens with the message box, pause menu, and map). So then you get the pretty fading effect without being able to see anything but the background and sprites, until it is completely finished and the level appears suddenly. The horizontal fades can work around this with sprites for the transparent parts, but vertical will flicker (sprite limit), and centered is just not possible at all.

**Comment by SkyTheLeafeon** [comment]
Hmm...

**Comment by andwn** [comment]
This is a "wontfix" palette fades are sticking around
