### ISSUE TITLE
Power Critter problems

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#254]
![doukutsu-v0_5_1a000](https://user-images.githubusercontent.com/36712090/37573831-27542698-2ad9-11e8-9c45-c4307915ffa9.jpg)

Hoo, boy.

**Comment by SkyTheLeafeon** [comment]
It's stuck in that block, and it jumps out of it when Quote gets close to it.

**Comment by andwn** [comment]
Nice, here is another favorite of mine
![2016-10-14-235536](https://user-images.githubusercontent.com/8164394/37574101-bd55ce2e-2af4-11e8-8595-5b293b937ab9.png)

By the way, the nightly hasn't been rebuilt since fixing the other critter issue (and all types of critters, except during the final battle, share the same AI routine). I can't even get the power critter to get on top of the block underneath where it is in that screenshot, for what it's worth.

**Comment by SkyTheLeafeon** [comment]
What the hell happened in that image? XD

**Comment by SkyTheLeafeon** [comment]
Curly looked kinda messed up back then, too. XD
