### ISSUE TITLE
Movement speed when jumping

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#262]
If I recall correctly, constantly jumping allows the player to move at a speed that's about 5% faster than walking. This doesn't seem to be currently present.

**Comment by andwn** [comment]
My engine should include this as of 0.5.0 (or maybe 0.4.0). How are you measuring this?

Friction is applied to the player while walking on the ground. This causes Quote's speed to fluctuate between 3 or 4 values around the maximum walking speed. While in the air, Quote will also stop speeding up after exceeding the maximum walking speed but the friction isn't applied, so it remains at this value instead of fluctuating (even if it happens to end up being way over the max walking speed).

It's easy to test, notice how Quote keeps his speed after being propelled by a (horizontal) fan instead of slowing down to the walking speed. As long as you keep holding the direction and never hit the ground or a wall Quote will stay at this speed. If you do hit the ground, The friction value will apply each frame Quote is touching it, but will not immediately lock below the max walking speed.

**Comment by SkyTheLeafeon** [comment]
For me, I pay attention to the speed at which the screen scrolls. It's clear that the speed difference is very subtle in most cases.

**Comment by Leo40Git** [comment]
Might be a problem with camera movement being off instead of Quote's speed being off.

**Comment by SkyTheLeafeon** [comment]
Ah, yes... That's definitely something to consider. An illusion! @Leo40Git

**Comment by andwn** [comment]
Most of the camera speeds I didn't test to be 1:1 but rather "close enough", especially the way it slowly moves over to one side of the player when turning.

There is also the matter of 50FPS vs 60FPS vs 60FPS-that-tries-to-be-50FPS-speeds.

I think the only way to know for sure would be to compare the average speeds (as in record the numbers) between PC and MD. Might do that eventually if I care enough.

**Comment by SkyTheLeafeon** [comment]
Gotcha. Accuracy is everything.

**Comment by andwn** [comment]
For me, accuracy comes second to keeping the gameplay smooth. Nobody wants to play a game that constantly slows to 50% speed. It's unplayable. When I play a botched slow port, I am always thinking "why didn't they just reduce that particle effect, this is awful, just change it".

There are times in the game where things are a bit different. A boss might spawn less minions, or cease doing so if more than a set number of them are already on screen. That's not what Pixel does, but do you really want to fight Omega and Muscle Doctor at half speed? I sure don't. Did you even notice they spawn less? Did you notice the Core is slightly smaller than the original game, or that Curly can sometimes override your max bullet count? Those things are different and if they weren't it would cause problems like slowdown or sprite flicker. Hell, Omega's legs DO flicker if there are enough power ups bouncing around.

I'm rambling at this point but yeah I plan on double checking the air speed at some point.

**Comment by SkyTheLeafeon** [comment]
...OK, so accuracy ISN'T everything. It's gameplay quality and hardware limitations that are to be kept in mind.

**Comment by andwn** [comment]
Closing this one too because if there really is a difference here it is incredibly subtle, and it may just be the camera. The screen is limited to move 8 pixels per frame because that is how fast the map is drawn while scrolling.
