### ISSUE TITLE
(Suggestion) A way to quit to the title screen without saving?

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#269]
Not sure if this is present in the PC version or not, but I remember Cave Story Plus having this feature.

**Comment by sikthehedgehog** [comment]
For what's worth it, you can already achieve the same thing by pressing the Reset button.

**Comment by andwn** [comment]
The annoying thing about this is that it would have to be in the pause menu (where on the screen would I even draw it?), where people are liable to hit it by accident, so i'd need to add another prompt asking if they are really sure. Then there will be 5 new bugs with this thing once it works at all and the burnout is settling in yet again. I just want this thing to be finished.

**Comment by SkyTheLeafeon** [comment]
I'll mark this as resolved since it's clearly too difficult to work with and probably wasn't in the original game to begin with.

**Comment by andwn** [comment]
It actually is in the PC version, if you press ESC there is a quit menu to press F1/F2 to restart or exit. The issue is mostly where I would put the option, how to activate it. The only thing reasonable is the item/weapon menu, but... how would I get it in there without making the menu more cumbersome? That is something I can't answer right now.

**Comment by SkyTheLeafeon** [comment]
...I would've said "can't you just reset?"
But, we're not going to go for that, are we?
