### ISSUE TITLE
(Suggestion) Noclip/walk through walls/freefly cheat?

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#277]
Could be an addition to the iSuckAtThisGameSHIT cheat.

**Comment by andwn** [comment]
This was a feature in like 2015 before anyone knew this repository existed, where you would hold A and float through walls. I don't plan on adding it back because it would introduce a can of worms (not fixing 50 issues of "game does a wrong thing when you go through walls in this part of that room").

**Comment by SkyTheLeafeon** [comment]
Hmm. What builds had this feature?

**Comment by andwn** [comment]
The very oldest one (Hold A and press start on the title screen)
https://github.com/andwn/cave-story-md/releases/tag/v0.1.0-alpha

The game crashes every time you try to load a save lol

**Comment by SkyTheLeafeon** [comment]
Even if you saved previously? XD

**Comment by SkyTheLeafeon** [comment]
I just messed with the February 7th build a bit. That's the oldest build in the repository.
Indeed, you can freefly by holding A. It actually looks pretty silly!
There's definitely no way out of the Grasstown Hut following the cutscene where you save Kazuma, though. An ancient issue that got addressed a long time ago.
