### ISSUE TITLE
Exact lines of text - differences

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#283]
There seem to be subtle differences between the lines of text in the MD version compared to the PC version. Are you sure you're using the Aeon Genesis translation?

**Comment by andwn** [comment]
The TSC files are the ones from the pre-patched game on cavestory.org (in 2015).

There are a few item descriptions/lines that were edited for length. Like I have less fingers than changes.

Also... why open an issue at all for something like this? Why does it even matter?

**Comment by SkyTheLeafeon** [comment]
I'm sorry?
I mean... good point. I just wanted it to be accurate.
But, accuracy isn't your thing. I'll close this issue now.

**Comment by andwn** [comment]
I'm somewhat drunk right now so don't take it personally.

I don't know what lines you think are different, but I know things get pretty different in the Nicalis translations. Maybe you compared with those by accident or maybe AGT has a newer version of the translation than the version cavestory.org provides.

The reason that the item descriptions specifically were edited is that, a line was longer than 36 characters causing the letters to go off to the right side of the message box (cause of the "small VRAM error" you mentioned recently). However, moving the last word on the line down made the next line too long, etc. So I had to get a bit creative, because the item descriptions absolutely NEED to be 3 lines or less. Otherwise you will only see the bottom 3 lines. That's the reason I had to fix the polar star description, it had an extra newline at the end of the 3rd line.

To explain my reasoning for not caring about this much... fan translations don't count as "the original game" to me. This was a translation made by some random person on the internet, not Pixel.

**Comment by SkyTheLeafeon** [comment]
The PC version in question isn't any of Nicalis' versions. It's the original, english-patched Doukutsu Monogatari, which is indeed from cavestory.org. 
I don't know if you're sober or not right now, but this might require doing a few comparisons.
...Unless you don't want to. Which is fine.

**Comment by SkyTheLeafeon** [comment]
...Actually, this might simply be a matter of me constantly skipping over every single line of dialogue in the MD version during all of the runs I've been doing. This could simply be a matter of me not even knowing what the dialogue says to begin with.
