### ISSUE TITLE
How to contribute music

### ISSUE THREAD

**Issue by vince94** [andwn/cave-story-md#298]
I've done a lot of experimentation with the XM dumps of the soundtrack, and used them in conjunction with various SPC conversion tools to make a [soundtrack mod](https://www.cavestory.org/forums/threads/cave-story-snes-soundtrack-mod.14225/) that turns the music into SNES renditions (they're more like a tribute/nod to the respective games I ripped the instruments from, and would take up too much cartridge space/wouldn't actually be usable if someone tried to make a version of the game for actual SNES hardware). While I've got a lot of other stuff I'm working on, I'm curious about contributing to this project's soundtrack as well. What kind of tracker/environment is needed to play back/make adjustments to these .vgm files? Does the music engine allow you to adjust instrument/FM synth parameters/add new instrument configurations?

**Comment by andwn** [comment]
The tracks were made in Deflemask. There are .dmf files for most of them that can be modified in that tracker. Some are missing, because those tracks were contributed to me with the .vgm file only. As .vgm is not a tracker format, they cannot be edited by any reasonable means.

The way I made them was manually note-for-note copy the XM from modplug tracker into Deflemask. Some channels were cut out or changed a bit. Case by case stuff. The FM instruments are either the built in ones or from [this huge archive](https://little-scale.blogspot.com/2013/02/all-sega-genesis-mega-drive-tfi.html). The PCM/drums are in the repository, and PSG instruments were created manually each time I used one.

If the tracker can do it XGM should be able to do it. Not sure if that answers your last question, I don't really know what it means.

**Comment by SkyTheLeafeon** [comment]
The whole soundtrack in general needs to be overhauled. But that can wait until beta, probably more towards final. Maybe in the final bugtesting stages.

**Comment by Leo40Git** [comment]
Somewhat related: I wonder if using an SMPS driver (like Sonic) is feasible. I'd imagine that would require decompiling/translating SMPS driver code to C, though...

**Comment by SkyTheLeafeon** [comment]
Are you saying that because the current driver isn't good enough? @Leo40Git

**Comment by Leo40Git** [comment]
@Leo40Git SMPS already has a tool for converting XM files into compatible songs.

**Comment by SkyTheLeafeon** [comment]
@Leo40Git Wait, what?
You're saying that we could literally take the entire original soundtrack of Cave Story and convert it to Genesis music that quickly? They didn't have to be replicated?

**Comment by vince94** [comment]
@SkyTheLeafeon Thanks!
I like the idea of using an XM conversion tool, but the number of channels would definitely need to be adjusted. I condensed all of them to eight channels for compatibility with the IT to SPC tool, so I could probably experiment with that

**Comment by andwn** [comment]
Was going to leave this alone but it seems a wild goose chase has started.... so:

I don't even know where to start on explaining why SMPS is a bad choice. Apart from the technical reasons, it's not legally sound to reuse Sega's proprietary code (then again, neither is using Pixel's assets).

There is not one SMPS. It is many similar formats which evolved over time in various first party Sega games. Every iteration of SMPS I know of has a single PCM channel (as opposed to 4 like XGM), and on top of that, the samples are 4 bits wide (instead of 8 like XGM). I would have to come up with a way to remake every sound in the game in an FM or PSG format instead of using PCM like it is now. 

These tools are for ROM hackers, and many are either specific to a single game or make you choose a format specific to a single game. I've used these tools before (for ROM hacking) and can tell you they are not exactly easy, even if you have a tutorial in front of you, and especially when you have to find and decide what instruments to use. If you want a Sonic ROM hack that uses Cave Story music that's fine, but making that music format work here is going to require a lot more than just an overhaul of the sound engine (or using a conversion tool to convert the SMPS to VGM... which kind of defeats the purpose, and the output VGM will almost definitely be too huge).


@vince94 I considered at one point writing a "xm2dmf" tool but decided against it because I thought it would be fine to just make the tracks myself. Don't know if someone else has made a similar tool and I can work on it sometime, but right now the way to do it is to create or modify .dmf files in Deflemask. There are 3 samples in [here](https://github.com/andwn/cave-story-md/tree/master/res/bgm/dmf/samples), then there are a bunch of instruments (in .tfi format) in that link from before.

**Comment by vince94** [comment]
Oh, right, I imagine even getting the SMPS sound engine working in the project would be a pain, if that sort of thing hasn't been done with homebrew projects before. Sorry for kind of assuming it'd magically work lol
I'll give the .dmf files a listen! And thanks for linking to that massive collection of instruments, making instruments from scratch was the main thing that had discouraged me when I first tried Deflemask a few months ago.

**Comment by SkyTheLeafeon** [comment]
I was about to say "Hey, throw in Sonic The Hedgehog's sound driver!" - but that's clearly not the right thing to do.

**Comment by DavisOlivier** [comment]
I used to make music on deflemask for fun back on 2016, i made some that are included in the game so i thought i could share some thoughts and in my experience.
I think this game's soundtrack sounds better when making less use of the "twang" effect the FM chip makes, also i believe i made a mistake putting the samples in high frequency because that may decrease the game's performance. Other than that i just made them like andwn did, opened the .xm files then transposed the notes to Deflemask but making tweaks so it sounds more accurate.
It's a boring work but the results are pretty compensating.

**Comment by andwhyisit** [comment]
@DavisOlivier: Did you actually mean "compensating" or was that an autocorrected typo of "compelling"?

**Comment by DavisOlivier** [comment]
I meant it worths the (imo)boring work, and the result is rewarding. But the result can be indeed compelling.

English is my secondary language

**Comment by andwn** [comment]
I'm late to respond here but the frequency of the music doesn't slow down the game since the audio is 99% handled by the Z80 CPU leaving the main processor to handle the rest of the game.

Basically if anyone else wanted to contribute music the only restrictions are:
It has to be a VGM file.
It has to be a reasonable size (don't stuff it with tons of WAV samples)

Going to put this in a CONTRIBUTING.md file.
