### ISSUE TITLE
Question about a claim in LICENSE.md

### ISSUE THREAD

**Issue by Clownacy** [andwn/cave-story-md#305]
In LICENSE.md, you claim:

> Graphics, Story, and Characters - Property of Studio Pixel
> 
> All created by Pixel, unless specified otherwise. I used them without permission. You absolutely can't use these in anything commercial. **Nicalis owns the exclusive rights (in the west at least).** Not to mention it would be pretty disrespectful to the original creator. 

Do you have a source for this? I'm working on a Cave Story-related project as well, and have been wondering about the legal status of the freeware version's assets for a while.

**Comment by andwn** [comment]
I'm no lawyer, but here is my thought process.

The closest thing freeware has to a license is what is in the readme:
このソフトはフリーソフトです。
実行中の事故は使用者各自の責任とします。
（制作に悪意が無いことをご理解ください）

This software is free.
There is no warranty, use it at your own risk.
(Please understand that there is no malicious intent)

It doesn't mention credit or whether or not you can make modifications, reuse any of the art, etc. So it's kind of like a software repository that doesn't have a license, where you're *probably* fine doing whatever with it, but if the author has a problem with that you have no rights to defend yourself.

On the Nicalis side, this is the only legal precedent I could find:
https://www.raspberrypi.org/forums/viewtopic.php?t=57754

Their only issue was with using the Cave Story name, RPi could continue bundling the freeware assets with NXEngine. I haven't been able to find any evidence that Nicalis has taken legal action because someone used assets (from freeware cave story).

**Comment by Clownacy** [comment]
The most blatant time I've seen Nicalis try to take down something for using the freeware assets was [when its CEO tried to use the modding forum as his personal army](https://www.cavestory.org/forums/threads/illegal-copy-of-cave-story-on-raspberry-pi-need-your-help.5063/), to attack that Pi NXEngine port for "stealing Pixel's art". That's not how I'd expect a company with full legal ownership of those assets to behave.

Even more absurdly, that blog post you linked mentioned a DMCA takedown notice, which is more like I'd expect, but rather than remove assets in response, they merely changed the name of their port. [The DMCA isn't for trademark violations](https://www.lexology.com/library/detail.aspx?g=13f9814f-b56e-4314-8e1b-95215ce60a6d). Not that it would make a difference anyway since [Nicalis's trademark of the Cave Story name expired in 2009](http://tsdr.uspto.gov/#caseNumber=77526825&caseSearchType=US_APPLICATION&caseType=DEFAULT&searchType=statusSearch). Not to mention the flip-flopping of 'you shouldn't use Pixel's art' one minute, and 'you shouldn't use the Cave Story name, we don't care about anything else' the next.

**Comment by SkyTheLeafeon** [comment]
Yeah, that's the complicated part. It's incredibly obfuscated and hard to come to a conclusion on.
