### ISSUE TITLE
Ceiling Physics

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#31]
There seems to be a difference in how physics work when hitting the ceiling. In vanilla CS there is a rebound effect, yet in CS MD the ceiling tiles become more of a jump limiter.

Here's some examples of this in action:
http://i214.photobucket.com/albums/cc164/andwhyisit/ceilingphysics1_zps7d4kuwbb.gif
http://i214.photobucket.com/albums/cc164/andwhyisit/ceilingphysics2_zpsvwlvwhzv.gif

Oh, and I figured I'd note while I am here that your port was mentioned in a magazine called Retro Gamer.

Sorry I haven't been playtesting of late.

**Comment by andwn** [comment]
Looking in the ceiling collision code the Y speed is set to 0 instead of the opposing direction, and it is especially bad on sloped ceilings because I forgot to disable holding the button to jump higher. For now I'm going to make it bounce off at half speed and fix it later if it turns out to still be inaccurate.

I've seen this project mentioned on a few sites. The attention is weird to me, but good motivation.

**Comment by andwhyisit** [comment]
Well... I was referring to a physical publication mind you, the type you buy off of a newsagent:
http://i214.photobucket.com/albums/cc164/andwhyisit/rgcsmd_zpsfgnhiahh.jpg

Anyhow I probably shouldn't use an issue tracker for personal discourse.

**Comment by andwn** [comment]
Well damn I wasn't expecting an actual magazine. Which issue? I've mostly just seen Sega sites mention it.

I don't really mind small talk in issues this isn't a professional project or anything. Speaking of the issue it seems even half speed is too much, makes it nearly impossible to grab the life capsule in egg corridor. I remember it was tricky to time but not this hard. I set a maximum bounce speed and will see how that works out.

**Comment by andwhyisit** [comment]
Issue 159,  page 104.

**Comment by andwhyisit** [comment]
Looking good. I'll mark this as closed.
