### ISSUE TITLE
Bug that you go on wall in start point

### ISSUE THREAD

**Issue by cavestoryfan1006** [andwn/cave-story-md#318]
![IMG_20191210_200132_828](https://user-images.githubusercontent.com/58753531/70576565-031dac80-1b88-11ea-8c6b-e26de77a7a88.jpg)

**Comment by cavestoryfan1006** [comment]
Also i run retro arch ps3

**Comment by andwn** [comment]
How did you get this to happen exactly? I'm unable to reproduce. What is the version it says on the title screen?

**Comment by SkyTheLeafeon** [comment]
I can't tell if that's out of bounds or not.

**Comment by Leo40Git** [comment]
![image](https://user-images.githubusercontent.com/7997354/72131391-beeb1b00-3384-11ea-9774-b11f982c5064.png)
Seems pretty accurate to me.

**Comment by andwn** [comment]
Actually, I did just get this to happen. You have to be far enough left of the ceiling that Quote will collide with the slope going down instead of the flat ground directly underneath the ceiling. Your X speed must also be 0.

I don't want to mess with the collision code again (I always break something else when I do) so I think I'm going to leave it. You can still just walk off the block as if you're on the ground.
