### ISSUE TITLE
Japanese text is VERY glitchy

### ISSUE THREAD

**Issue by BTTRG** [andwn/cave-story-md#322]
IDK if this was fixed in 0.6.0, It wasn't in 0.5.2, But the japanese text is pretty glitchy. The title of maps are just glitched Kanji, plus on the far right of the screen there are some messed up tiles near the text box. Sadly, the version of Picodrive that I used to test the japanese test didn't support screenshots, and I lost the photos I took directly of my handheld's screen that documented alot of other sprite and VRAM bugs.

**Comment by andwn** [comment]
The map name text was fixed before 0.6.0, but not the text box. I'm aware of that though.

**Comment by BTTRG** [comment]
Thanks. I double checked and it was fixed in 0.6.0. Also, I compared the text box glitch with 0.5.2 vs 0.6.0. In 0.5.2, The glitching is a lot more random. However, in 0.6.0, The text box glitch usually displays a white and red missile with a few bubbles near it. Also, why does the "Boss" in boss battles turn into a bubble with Japanese?

**Comment by BTTRG** [comment]
Thanks. I double checked and it was fixed in 0.6.0. Also, I compared the text box glitch with 0.5.2 vs 0.6.0. In 0.5.2, The glitching is a lot more random. However, in 0.6.0, The text box glitch usually displays a white and red missile with a few bubbles near it. Also, why does the "Boss" in boss battles turn into a bubble with Japanese?

**Comment by andwn** [comment]
The japanese text rendering works in a different way that requires a lot more VRAM, and there isn't much to spare. One of the places it gets stored is where the map name is (so the map name disappears when the text window opens). I'll have to do a similar workaround for the boss bar I think.

**Comment by DreamPlusInfinity** [comment]
I tried it in Japanese and it's really harmed by the fact there's only two lines instead of 3. The formatting is very messed up because of that.

I strongly suggest you use a 12x12 pixel font, and a limitation of 3 lines and 20 full width characters (less than the entire horizontal width at 24 characters/288 pixels). That will be around 150 tiles max.

I'm guessing you're using a 16x16 font because you don't want to deal with characters divided across different tiles, but it's straightforward enough for a fixed width 12x12 pixel font. 
Splicing characters vertically is as easy as copying the next glyph on top of the glyph meant to be directly above it, and splicing characters horizontally isn't that hard considering each 12x12 character is "an 8px wide complete tile + 4px wide partial tile" OR "a 4px wide partial tile + 8 px wide complete tile". The ROM can be made to host two copies of the font, one shifted 4 px to the right in advance, to minimize any extensive processing aside from an OR operation.

**Comment by sikthehedgehog** [comment]
4px is a 16-bit word, so no need to actually do any OR stuff (just moving words will do).

**Comment by andwn** [comment]
I've considered doing something like this but after spending a pretty long time looking for a suitable 12 pt Japanese bitmap font I ended up empty handed.

**Comment by DreamPlusInfinity** [comment]
You can try [this one](https://github.com/hajimehoshi/mplus-bitmap-images). It's based on the M+ BITMAP FONT project. The kanji font is partial and only includes jouyou kanji but it's at least purely non-proprietary. (If that wasn't a concern, then it would be easier to use fonts from the GBA/DS, such as the Japanese version of Harvest Moon or something similar)

Even as a placeholder, it beats things like the Unifont (Linux' pixel font that covers as much unicode characters as possible, but with questionable artistic affinities...)

> 4px is a 16-bit word, so no need to actually do any OR stuff (just moving words will do).

That would make it possible to support half width characters (English, numbers, basically the ASCII set... like with "タマゴNo.03" in the first zone) with 6 px wide characters (that would be 3 bytes) though idk if it wouldn't be easier to just use full width characters for that instead.

**Comment by andwn** [comment]
New font renderer is bug free

<img width="624" alt="Screen Shot 2022-01-18 at 18 56 39" src="https://user-images.githubusercontent.com/8164394/150037932-6ac21e20-0722-4b87-90e9-da02cfd41230.png">

**Comment by andwn** [comment]
Getting there

<img width="632" alt="Screen Shot 2022-01-20 at 20 36 06" src="https://user-images.githubusercontent.com/8164394/150449717-774d6372-15e1-4e94-b003-8b3d1090641a.png">

**Comment by andwn** [comment]
0.8.0
There may still be glitches I didn't see from the new font renderer but can handle those case by case
