### ISSUE TITLE
Music playback semi-broken on PAL

### ISSUE THREAD

**Issue by vaguerant** [andwn/cave-story-md#327]
Please check before continuing:
- [x] I've searched my issue or question to make sure it has not been reported/answered already
- [x] I've checked [COMPATIBILITY.md](/andwn/cave-story-md/blob/master/doc/COMPATIBILITY.md) to make sure my emulator or system is known to work
- [x] I understand there is no physical release and you are not responsible for issues with bootlegs
- [x] This is a bug or question and not a feature request

First off, I should note that in order to test on Genesis Plus GX, I had to modify the header of the latest build, as [described by Eke-Eke here](https://github.com/ekeeke/Genesis-Plus-GX/issues/333#issuecomment-687865990). You're better off reading Eke-Eke's explanation, but if I understood correctly, you're using a modified header in order to fool certain emulators into running with a specific mapper, but the mapper implied by that change (and chosen by GPGX based on that header) is not correct for this game.

On to the actual meat of the issue: music seems to sometimes be broken on PAL. While this does occur during gameplay, the easiest way to reproduce it is to cycle through tracks in the Sound Test until something doesn't play. The first note (possibly of the percussion track only?) seems to play, and then there's complete silence afterward, until the next music load, at which point the music either will or won't play in the same way.

I can get the issue to reoccur easily, but I can't find a reliable *trigger* for the issue in my testing, i.e. it's unpredictable to me whether or not the issue will occur each time new music begins, but it doesn't take many attempts to get it to happen, I'd say at least one in five attempts to play music fails in this way. The same issue does not occur in my testing while running as NTSC. That and the intermittent nature of the issue makes me wonder if it's related to timing in the sound engine, but that's purely a guess.

I tested on the latest build of Genesis Plus GX on Wii, the currently somewhat outdated Libretro build of Genesis Plus GX on Wii U (it hasn't pulled in changes from upstream in a while), as well as the latest BlastEm for Windows. All three emulators had identical behavior as far as I was able to tell in my testing.

**Comment by andwn** [comment]
It sounds like there is a pretty pervasive misunderstanding about that header if it's really only meant to be used for Krikkz stuff. My implementation of the Sega SSF mapper was based on a combination of [this page](https://plutiedev.com/beyond-4mb) and [SGDK's implementation](https://github.com/Stephane-D/SGDK/blob/master/src/boot/rom_head.c#L25). I'll link to them what Eke-Eke said.

As for the music, I've been changing around the code every so often since I keep running into problems. I've seen other folks having the [same issues](https://github.com/Stephane-D/SGDK/issues/117) and have tried various advice. 

In 0.5.0 and 0.6.0 I call XGM_Stop, freeze the game for a couple frames, then call XGM_Play. That works 99% of the time, but occasionally something funky happens, and for a full second the previous track plays back in hyper-speed. 

In the latest build you have I decided to use XGM_Pause instead of XGM_Stop and remove the freeze. However it turns out that a Pause followed by a Play ends up being executed out of order. I made it freeze for only 1 frame, but it seems that is only good enough for NTSC. Will have to play with this more or just revert it to what 0.6.0 did.

**Comment by andwn** [comment]
Did the game start in Blastem with "SEGA MEGA DRIVE" in the header? I get a Segmentation fault.

Really seems like nobody can agree on how to handle the mapper and I'm better off making 8 ROMs for multi-language support instead.

**Comment by andwn** [comment]
And here are the results from an X7

SEGA SSF: Saving doesn't work, but there is no crash so Bank 0 isn't moving.

SEGA MEGA DRIVE: ERROR: 3E - Large size games conflicts with 32x and SEGA-CD hardware.

Sounds like it's not trying to use any mapper at all without SSF.

I give up. Separate ROMs it is.

**Comment by andwn** [comment]
[doukutsu.zip](https://github.com/andwn/cave-story-md/files/5186303/doukutsu.zip)

...and here we are, back to 4MB. English only. Will figure out something for other languages over the next couple days.

The music in the sound test isn't messing up for me on PAL with this, so hopefully it doesn't come up in gameplay either.

**Comment by vaguerant** [comment]
Sorry for the delay. Yes, I get the same thing on BlastEm with the old >5MB ROM. It works with the SEGA SSF header, but fails with the SEGA MEGADRIVE or SEGA GENESIS header. And of course, the reverse behavior on Genesis Plus GX, SEGA MEGADRIVE works but SEGA SSF does not. Seems like somebody needs to get the emudevs onto the same page.

And again, same as your experience, the PAL music seems to work fine in the new 4MB ROM across both,

**Comment by sikthehedgehog** [comment]
For bonus points, Mega Everdrive implements its extended mapper differently than Sega mapper (`$A130F0`'s behavior is different and this actually breaks saving).

**Comment by ekeeke** [comment]
Yes, it should not crash when writing to A130F1h because Krikzz extender mapper needs a 16-bit write (to A130F0h) to remap bank 0, with a protection bit (bit 15) , which Genesis Plus GX does not correctly emulate (I need to correct this to better match everdrive hardware behavior)

That said, that mapper is not designed to enable/disable SRAM in upper 2MB range on 
 A130F1h write so "SEGA SSF" header should NOT be used if you rely on SEGA "official" SRAM bankswitching... and emulators should not enable official SRAM bankswitching if that string is found, only ROM bankswitching.

Again, that string was "invented" by Krikzz something like 6 years ago to identify games relying extended SSF2-like ROM bankswitching but it was not made compatible with official SRAM bankswitching used in a few games (Sonic 3, Phantasy Star IV and Beyond Oasis / Story of Thor) and instead extended SSF2-like ROM bankswitching to bank 0.

A convention for emulators could be to:

1) enable SSF2 extended mapper if "SEGA SSF" string is found. This mapper can use SRAM in a different way (by selecting one of the ROM bank and by enabling ROM write in A130F0h) but it can be used if you don't need SRAM but only SSF2-like ROM remapping.

otherwise,

2) enable official SRAM bankswitching mapper by default (A130F1h writes) in case backup RAM is enabled in ROM header and start address specified in header is within ROM specified range

3) enable SRAM + SSF2-like ROM bankswitching mapper by default if backup RAM is enabled in ROM header and ROM size is larger than 4MB

4) enable linear ROM mapper if no backup RAM is specified and ROM size is larger than 4MB

**Comment by sikthehedgehog** [comment]
I wonder how much of this mess would be avoided if we ditched raw binary dumps and started attaching proper metadata indicating what's in the cartridge so we can ignore the ROM header for good (just don't pull off a Higan with its folder-per-game setup, at least put all files into a glorified ZIP archive if you're gonna do that). I know that there are also people who want to replace the Sega mapper altogether because it's "too complex", as well as custom hardware that the ROM header can't accomodate at all, and it'd also help solve the mess that's EEPROM mappings.

Hey Eke since you're here, I know BlastEm's author is willing to do it but he wants at least your word on it because he doesn't want to make it a single-emulator format.

**Comment by ekeeke** [comment]
Ditching raw binary dumps will unlikely ever happen as it is a little bit extrem and unecessary for most games but yes, I already thought about it and this is definitively the best way to handle this for new games that rely on specific cartridge hardware.

I think it is kinda hard to find a good convention that would handle all possible hardware cases while remaining easily understandable by both game developers and emulators but I would definitively support this idea. Just don't use xml (txt file is much more readable) and make sure we to ask review of the specification from several MD emulators AND homebrew developers.

**Comment by Stephane-D** [comment]
@andwn I fixed some issues with the way commands were interpreted from the XGM driver. There were some race condition leading to some potentials issues as the ones you described.
I recommend to not use XGM_stop() command but XGM_pausePlay() instead (which is faster to apply), thanks to Matt from BigEvilCorp who pointed a bug which could let remaining sound even after the pause command (DAC write wasn't properly restored).
