### ISSUE TITLE
Saves are missing on ATGames Sega Genesis handheld

### ISSUE THREAD

**Issue by Wumbo2255** [andwn/cave-story-md#333]
I noticed while trying to play using the "Sega Genesis Ultimate Portable Game Player" that the saves were gone. I was using Neto Boot Loader to fix the music and to enable save state, so I was surprised by this.

**Comment by thomasgoldstein** [comment]
You're talking about the in-game save feature not working and not save states, right? Just asking since you also mention save states.

Anyway, ATGames consoles have a bad reputation, and looking around, I've found this: https://www.reddit.com/r/SEGAGENESIS/comments/7v0szr/why_doesnt_my_atgames_portable_sega_genesis_save/
So my guess would be that the problem is your console, not the game.

Do saves work with other games?

**Comment by Wumbo2255** [comment]
Sorry, I meant that the icons themselves were missing from the game. For example, at the starting point, the refill terminals are still there, but the save disk's sprite is gone. When I attempted to interact with where it was before, nothing happened, so I'm guessing that it isn't that the sprite is glitched and doesn't appear.
Also, saves do work in other games. The Neto Boot Loader lets you save the game to the sd card, since the handheld can't on its own.
![image](https://user-images.githubusercontent.com/61855201/102722687-cd4df080-42d0-11eb-852e-be569b58f78f.png)

**Comment by AnotherLife** [comment]
Read the FAQ:

https://github.com/andwn/cave-story-md/blob/master/doc/FAQ.md

It is an emulator issue. Are there any options you can change?

**Comment by Wumbo2255** [comment]
No, thank you for your help.
