### ISSUE TITLE
Textbox woes (pre-sandzone)

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#39]
I'll let the images do the talking this time.

See here:
http://i214.photobucket.com/albums/cc164/andwhyisit/itsjustgravey_zpspsttwkbu.gif

8 cases of miscentred sign text.
2 cases of sticky non-scrolling characters.
2 cases of text cutoff.
2 cases of missing item images.

**Comment by andwn** [comment]
The missile pickups in ArmsImage were missing so it drew nothing 39a63c16f22613d841cf8a0ca2621e83af766d7b

I fixed the cutoff/stickyness hopefully. Increased the size of the window but forgot to expand the value for number of characters in a couple functions.

The signs... no idea. Maybe Pixel decreased the width of spaces.

Since I'm already working on the window adding <MS2 would be good so you can actually see the characters in the scene before the Omega fight.

**Comment by andwhyisit** [comment]
Well the original font in 320x240 windowed mode rendered each character 6px wide, so differences in text rendering are to be expected.

**Comment by andwhyisit** [comment]
Sorry, I miscalculated the last two earlier. I've edited my previous comment with the correct figures.

**Comment by andwn** [comment]
Thanks I'll try that out.

By the way I broke bullets don't try the game again yet ;;;

**Comment by andwhyisit** [comment]
The only thing left is the silver locket text. I think the only way around that is to use 4 lines of text (accessing the fourth via scrolling).

I'm thinking of writing a cron job to automatically generate nightly builds if you don't mind, since I am already using my web server for compiling builds and it would help others to find bugs as well. What time of the night are you least likely to make a commit, and what timezone?

**Comment by andwn** [comment]
That would be convinient! I'm almost always sleeping 6-10 UTC (2-6 AM for me). 

For the locket I just changed the text. Easier than coding around it.

![Image](https://my.mixtape.moe/niameh.png)
