### ISSUE TITLE
[EN] Several text strings are too long -- suggested fixes

### ISSUE THREAD

**Issue by SeventhSentinel** [andwn/cave-story-md#390]
**What happened**
Several strings of text are too long and draw over or beyond the text box borders.

**Expected behavior**
While I have not been able to comb through the whole game yet, a good start would be to replace these strings in ArmsItem.txt:
```
- 65: recently has taken up sleeping in them.<WAI9999<END
+ 65: lately has taken up napping in them.<WAI9999<END
- 68: to poor eyesight, he roams the darkness
+ 68: to poor eyesight, he roams the dark
- 325: warrior you would trust your back to.
- 326: Surely you will meet again one day...<WAI9999<END
+ 325: warrior you'd trust your back to.
+ 326: Surely you'll meet again one day...<WAI9999<END
```
I'm not that experienced in GitHub and was not able to figure out how to make a pull request for this. I think I need to be given write access if you'd like me to implement these fixes myself.

**Screenshots**
![image](https://github.com/andwn/cave-story-md/assets/19996267/3d646c82-9913-484a-924d-e4c719be82d5)

**Version**
0.8.1 Snapshot from 5/27/2024, English: doukutsu-en-202405270015.bin

**Environment**
Kega Fusion v3.64, Windows 10

**Comment by thomasgoldstein** [comment]
You should not need write access here. As far as I know, you need to fork this repo, make the changes on your forked repo, then submit a pull request to this one. For details, see: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

Let me know if you can't get it to work.

**Comment by andwn** [comment]
Oh hey, thanks for this. I recall at one point I had to slightly change some item descriptions to fit but guess I missed some... and I definitely haven't combed very long over the other languages.

A potential alternative could be to increase the window width so it goes all the way to the edges of the screen, allowing 38 letters per line instead of 36. Problem with that is the text on the sides would be outside of the "TV Safe" area, so it would look fine on many TVs but some will cut it off.
