### ISSUE TITLE
Crash in terminal room in Egg Corridor

### ISSUE THREAD

**Issue by sikthehedgehog** [andwn/cave-story-md#45]
If you go back to the terminal room in Egg Corridor after getting the ID card and disabling the shield, the game hangs. According to BlastEm: `Read from VDP data port while writes are configured, CPU is now frozen. VDP Address: 2, CD: 5`

(this also ironically hung up BlastEm itself as well and I had to kill the process, but that's a different matter lol - stop breaking the emulator jeez)

EDIT: er right, this is after disabling the shield, not just getting the card.

**Comment by andwn** [comment]
I can't get BlastEm to build for the life of me, so I'll try on an Everdrive.

What's "CD"?

**Comment by sikthehedgehog** [comment]
BlastEm builds easily on Linux, not so easily on Windows...

Anyway, CD is one of the VDP control bits (every 32-bit command has five control bits). It's also quite a pain to explain what each of them actually do (CD4 and CD5 are related to the DMA hardware, and the explanation isn't exactly trivial). Either way, the implication here is that something got messed up while it was trying to do something with the video hardware.

**Comment by andwn** [comment]
I'll try to build it again. Last time I tried was a couple months ago. Building was no problem, but launching it complained about a missing library. Neither searching my distro's repos or Google gave me anything so I gave up.

I use DMA a lot, but don't know shit about how it works because SGDK makes it too easy. DMA_doDma() that's it do the thingy. Catching the line in GDB that locks up is probably my best bet.

**Comment by mikepavone** [comment]
For what it's worth, when I gave the game a try in BlastEm I did not get the crash/freeze at that location, but a bit further in the game (the house with the fireplace in Grassland). I have a save file at that point and it's not 100% consistent on triggering the problem there either.

Anyway, I did some digging (poking around in BlastEm in gdb is not fun if you're not used to reading the code the 68K core generates at runtime) and it looks like the problem is that sometimes a vertical interrupt occurs during a call to VDP_getPaletteColors (which is in turn called by VDP_fadeTo). Personally, I think this could be considered a bug in SGDK itself. VDP_getPaletteColors should probably disable interrupts write before setting up reads on the VDP and then turn them back on after it's done reading the current palette. That said, you can probably fix this by doing a VDP_waitVSync before calling VDP_fadeTo.

**Comment by andwn** [comment]
Thanks for the help debugging. Took a look at vdp_pal.c and that makes sense. I'll disable interrupts before calling the async fade, and call VDP_waitVSync() before the blocking ones.

And I just figured out what I was doing wrong building BlastEm... `make` instead of `make blastem`. One of the tools failed to build and I thought that meant the whole thing failed.

**Comment by andwn** [comment]
Ok, running BlastEm I went back to the Egg Observatory after defeating Igor. The issue does not seem to occur anymore. I even tried mashing the down button to try and break it for a while.

[doukutsu.zip](https://github.com/andwn/cave-story-md/files/545323/doukutsu.zip)

**Comment by mikepavone** [comment]
Sorry about the broken default target for BlastEm. I'm not as good as I should be at verifying that all the little utilities still build when I'm making changes to the main emulator.

I can confirm that I'm no longer able to reproduce the bug with the updated version.

**Comment by andwn** [comment]
No big deal. It could be much worse, like erroring out in the last step of an hour build process because of a dependency missing.

I've been playing further on and have resolved a couple more crashes.  One when entering Sand Zone, and another after the large door opens at the beginning of Labyrinth. Both involved trying to load sprite tiles from invalid locations.

**Comment by mikepavone** [comment]
Awesome, I was just about to file a bug about the Sand Zone issue, but you've already gone and fixed it!

**Comment by andwn** [comment]
Even more issues going on wheich should now be resolved. I've reached the bad ending on BlastEm.
