### ISSUE TITLE
Horizontal flying beetle logic

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#62]
The horizontal flying beetles should only fly across when the player is in line with them on the y axis, however in the MD version they fly all the time.

Original:
http://i214.photobucket.com/albums/cc164/andwhyisit/lazybeetle_zpshrs5axkt.gif

MD version:
http://i214.photobucket.com/albums/cc164/andwhyisit/hyperbeetle_zpsxauvvhxw.gif

**Comment by andwn** [comment]
This "should" be fixed but I'm too lazy to switch out of my labyrinth save while fixing the backgrounds/bosses in that area.

**Comment by andwn** [comment]
I tested and they uhh... float in the middle. So I'll make them by default fly once, then wait for you to approach.

**Comment by andwn** [comment]
Ok, changed the initial state to move to the facing wall when the enemy first appears.

Unrelated. I've been experimenting with getting rid of the variable time step because it's a huge pain to manage. That would mean NTSC being a bit faster, but then there won't have to be separate PAL and NTSC ROMs. What do you think?

TV standards suck by the way.

**Comment by andwn** [comment]
This feels wrong actually... faster than CS+. Maybe not.
