### ISSUE TITLE
The amazing technicolor Labyrinth

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#64]
![](http://i.imgur.com/MJZCRjl.gif)
![](http://i.imgur.com/lIOM7MC.gif)
I think the pictures speak to themselves.
Labyrinth M's background is fine.

**Comment by andwn** [comment]
The parts between monster x and core are in the process being reworked today. Try to report against nightly which I try to keep more stable.

**Comment by Leo40Git** [comment]
In the nightly build, Labyrinth B's background appears normal, but Boulder Chamber is missing it's background.

**Comment by andwn** [comment]
Labyrinth B's background was bkMaze instead of bkBlue. There are a bunch of other backgrounds in the late game that are wrong and I'm swapping them all around. Like Waterway and Plantation should be bkGreen not bkGray.

The problem with this now is the palettes in use are different than where the backgrounds are usually used so I have to go through the game and make recolored copies of whatever is off color (and hopefully finish before the next nightly).
