### ISSUE TITLE
Glitched door after boss fight in power room

### ISSUE THREAD

**Issue by sikthehedgehog** [andwn/cave-story-md#67]
In the Balrog fight in the power room in Grasstown (the one right after you turn on the power), after defeating Balrog part of his sprite will overwrite the door, making the door look like chunks of Balrog.

I only went through the fight once during this test but still shows something is wrong here.

**Comment by andwn** [comment]
This has been randomly happening in a few rooms lately and i'm not sure why. Either the door is freeing its VRAM space when it shouldn't or balrog is not properly checking the space is in use.

**Comment by sikthehedgehog** [comment]
I suppose it'd be easier to check for the door first?

**Comment by andwn** [comment]
I think the root cause of this was with the DMA queue (didn't disable interrupts while adding to it). I'm not doing any VDP stuff in the Vint routine anymore so it's unlikely this will ever happen again.

**Comment by SkyTheLeafeon** [comment]
Has this been resolved?

**Comment by andwn** [comment]
No idea. I thought it was fixed before but then it happened to someone else. Still hasn't happened to me since.

**Comment by andwn** [comment]
Going to continue to watch this issue in #182 and #303 since they have screenshots.

I've made a couple minor fixes to related things but I'm not sure if either will help:
- For <CMP, delete the object being replaced BEFORE creating its replacement.
- There were a couple functions that clear all objects of a specific type or id2, but they didn't de-allocate the sprites. Well, now they do.
